language: ruby
rvm:
  - "2.1.2"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database hotornot_test;' -U postgres

script: 'bundle exec rake'
