language: ruby
rvm:
  - "2.1.2"
addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database hotornot_test;' -U postgres

script: 'CODECLIMATE_REPO_TOKEN=4071671b853044bfddfc7b3ee18e5b4d5c06ff730f545e08816f12877877fdf5 bundle exec rake'
